services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: exporter-ease-app
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    environment:
      - NODE_ENV=production
    restart: always
