"use client"

import { createContext, useContext, useState, useEffect, ReactNode } from 'react'

interface LanguageContextType {
  language: string
  setLanguage: (lang: string) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

// Translation dictionary
const translations: Record<string, Record<string, string>> = {
  en: {
    // Navigation
    "about_us": "About Us",
    "services": "Services",
    "video_tutorial": "Video Tutorial",
    "support": "Support",
    "login_register": "Login / Register",
    "english": "English",
    "hindi": "हिन्दी",
    "marathi": "मराठी",
    
    // Hero Section
    "revolutionizing_agriculture": "🌾 Revolutionizing Agriculture",
    "welcome_to": "Welcome to",
    "gofarmlyconnect": "GoFarmlyConnect",
    "hero_description": "Transform your farming operations with our comprehensive digital platform. Join thousands of farmers who have increased their productivity by 40% using our innovative solutions.",
    "get_started_free": "Get Started Free",
    "watch_demo": "Watch Demo",
    "active_farmers": "Active Farmers",
    "trade_volume": "Trade Volume",
    "uptime": "Uptime",
    "latest_updates": "🚀 Latest Updates",
    "ai_crop_prediction": "🌾 New AI crop prediction system - Increase yield by 40%",
    "mobile_app_launched": "📱 Mobile app launched - Manage your farm anywhere",
    "special_financing": "💰 Special financing for small farmers - Apply now",
    
    // Services
    "our_services": "Our Services",
    "comprehensive_solutions": "Comprehensive Import Export Solutions",
    "services_description": "Everything you need to streamline your international trade operations and ensure compliance",
    "gst_filing": "GST Filing",
    "gst_description": "Simplify your Goods and Services Tax (GST) compliance with easy online filing.",
    "automated_gst_returns": "Automated GST Returns",
    "input_tax_credit": "Input Tax Credit Management",
    "reconciliation_tools": "Reconciliation Tools",
    "audit_support": "Audit Support",
    "iec_registration": "IEC Registration",
    "iec_description": "Obtain your Import Export Code (IEC) quickly and hassle-free for international trade.",
    "new_iec_application": "New IEC Application",
    "iec_modification": "IEC Modification",
    "iec_renewal": "IEC Renewal",
    "consultation_services": "Consultation Services",
    "dsc_procurement": "DSC Procurement",
    "dsc_description": "Secure your Digital Signature Certificate (DSC) for online document authentication.",
    "class3_dsc": "Class 3 DSC",
    "organization_dsc": "Organization DSC",
    "individual_dsc": "Individual DSC",
    "renewal_services": "Renewal Services",
    "icegate_services": "ICEGATE Services",
    "icegate_description": "Seamlessly interact with ICEGATE for customs clearance and trade-related services.",
    "bill_of_entry": "Bill of Entry Filing",
    "shipping_bill": "Shipping Bill Processing",
    "duty_payment": "Duty Payment",
    "status_tracking": "Status Tracking",
    "adcode_registration": "AD Code Registration",
    "adcode_description": "Register your Authorized Dealer (AD) Code for smooth export transactions.",
    "adcode_reg": "AD Code Registration",
    "bank_linkage": "Bank Linkage",
    "export_incentives": "Export Incentives",
    "compliance_checks": "Compliance Checks",
    "other_documents": "Other Document Filing",
    "other_documents_description": "Comprehensive support for various other import-export related document filings.",
    "rcmc_application": "RCMC Application",
    "meis_seis_claims": "MEIS/SEIS Claims",
    "epcg_license": "EPCG License",
    "advance_authorization": "Advance Authorization",
    "learn_more": "Learn More",
    "ready_to_streamline": "Ready to Streamline Your Trade Operations?",
    "join_thousands": "Join thousands of importers and exporters who have digitized their operations with GoFarmlyConnect",
    "get_started_today": "Get Started Today",
    
    // Features
    "why_choose": "Why Choose GoFarmlyConnect",
    "built_for_modern": "Built for Modern",
    "farmers": "Farmers",
    "features_description": "We understand the unique challenges farmers face. That's why we've built a platform that combines cutting-edge technology with deep agricultural expertise.",
    "lightning_fast": "Lightning Fast Processing",
    "lightning_description": "Process documents and applications in minutes, not hours or days",
    "bank_grade_security": "Bank-Grade Security",
    "security_description": "Your data is protected with enterprise-level encryption",
    "expert_support": "Expert Support",
    "expert_description": "24/7 customer support from agricultural experts",
    "proven_results": "Proven Results",
    "results_description": "Average 40% increase in productivity for our users",
    "save_time": "Save Time",
    "time_description": "Reduce paperwork time by up to 80% with automation",
    "compliance_100": "100% Compliance",
    "compliance_description": "Stay compliant with all regulatory requirements",
    "happy_farmers": "Happy Farmers",
    
    // Dashboard
    "dashboard": "Dashboard",
    "profile": "My Profile",
    "progress": "Progress",
    "documents": "Documents",
    "settings": "Settings",
    "registration": "Registration",
    "logout": "Logout",
    "welcome": "Welcome",
    "complete_profile": "Complete your profile to get started",
    "upload_document": "Upload Document",
    "document_uploaded": "Document uploaded successfully",
    "document_verified": "Document verified",
    "document_rejected": "Document rejected",
    "pending_verification": "Pending Verification",
    "re_upload_required": "Re-upload Required",
    "profile_completion": "Profile Completion",
    "basic_information": "Basic Information",
    "required_documents": "Required Documents",
    "email_verified": "Email verified",
    "mobile_verified": "Mobile verified",
    "upload_successful": "Upload Successful",
    "upload_failed": "Upload Failed",
    "email_required": "Email Required",
    "enter_email": "Please enter an email address",
    "file_too_large": "File Too Large",
    "file_size_limit": "Please upload a file smaller than 1MB",
    "supported_formats": "Supported: PDF, JPG, PNG (max 1MB)",
    "loading": "Loading...",
    "error": "Error",
    "failed_to_load": "Failed to load profile data",
    "try_again": "Try Again",
    
    // Dashboard specific
    "notifications": "Notifications",
    "tutorials": "Tutorials",
    "video_tutorials": "Video Tutorials",
    
    // Services/Import Export
    "simplify_import_export": "Simplify Your Import Export",
    "import_export_solutions": "Import Export Solutions",
    "simplify_your": "Simplify Your",
    "import_export": "Import & Export",
    "hero_content_description": "Complete digital platform for import-export documentation, customs clearance, and trade compliance. Process your shipments 70% faster with our automated filing system.",
    // Partners & Integrations
    "trusted_partners": "Trusted Partners",
    "our_partners_integrations": "Our Partners & Integrations",
    "partners_description": "Working with leading government bodies, financial institutions, and technology partners to create a comprehensive agricultural ecosystem",
    "government_partners": "Government Partners",
    "banking_partners": "Banking Partners",
    "tech_integrations": "Tech Integrations",
    "compliance_rate": "Compliance Rate",
    
    // Testimonials  
    "success_stories": "Success Stories",
    "what_farmers_say": "What Farmers Say About Us",
    "testimonials_description": "Join thousands of satisfied farmers who have transformed their agricultural operations with GoFarmlyConnect",
    "average_rating": "Average Rating",
    "happy_farmers_count": "Happy Farmers",
    "satisfaction_rate": "Satisfaction Rate",
    "support_available": "Support Available",
    
    // Learn with us
    "learning_resources": "Learning Resources",
    "learn_with_gofarmly": "Learn With GoFarmlyConnect",
    "learn_description": "Master modern agricultural techniques and digital farming solutions with our comprehensive video tutorials and expert guidance",
    "view_all_tutorials": "View All Tutorials",
    "watch_now": "Watch Now",
    "views": "views",
    
    // Tutorial titles
    "farm_registration_title": "Complete Farm Registration Process",
    "crop_management_title": "Advanced Crop Management Techniques",
    "financial_planning_title": "Financial Planning for Farmers",
    "market_analysis_title": "Market Analysis and Price Trends",
    "digital_transformation_title": "Digital Transformation in Agriculture",
    
    // Export Registration Tutorial
    "overall_registration_progress": "Overall Registration Progress",
    "journey_to_export_ready": "Your journey to becoming an export-ready business",
    "overall_progress": "Overall Progress",
    "track_your_progress": "Track Your Progress",
    "learn_how_to_become_exporter": "Learn How to Become an Exporter",
    "watch_step_by_step_tutorials": "Watch our step-by-step tutorials to understand the export registration process",
    "getting_started": "Getting Started",
    "introduction_export_basics": "Introduction to export business basics",
    "min_watch": "min watch",
    "complete_registration_guide": "Complete Registration Guide",
    "step_by_step_registration": "Step-by-step registration process walkthrough",
    "featured": "Featured",
    "document_preparation": "Document Preparation",
    "required_documents_preparation": "Required documents and how to prepare them",
    "view_all_video_tutorials": "View All Video Tutorials",
    "progress_remaining": "remaining to complete your export registration",
    "registration_complete": "🎉 Registration complete! Ready to start exporting.",
    
    // Tutorial categories
    "getting_started_category": "Getting Started",
    "management_category": "Management",
    "analytics_category": "Analytics",
    "finance_category": "Finance",
    "logistics_category": "Logistics",
    
    // FAQ
    "got_questions": "Got Questions?",
    "frequently_asked_questions": "Frequently Asked Questions",
    "faq_description": "Find answers to common questions about GoFarmlyConnect's features, pricing, and how to get started",
    "still_have_questions": "Still have questions?",
    "support_team_help": "Can't find the answer you're looking for? Our support team is here to help you 24/7",
    "contact_support": "Contact Support",
    "schedule_call": "Schedule a Call",
    
    // Contact Us
    "get_in_touch": "Get In Touch",
    "contact_us": "Contact Us",
    "contact_description": "Ready to transform your farming operations? Get in touch with our agricultural experts for personalized guidance",
    "helpdesk_24x7": "24x7 Helpdesk",
    "toll_free": "(Toll Free)",
    "available_round_clock": "Available round the clock",
    "email_support": "Email Support",
    "response_within_2hours": "Response within 2 hours",
    "whatsapp_support": "WhatsApp Support",
    "quick_assistance_chat": "Quick assistance via chat",
    "head_office": "Head Office",
    "support_hours": "Support Hours",
    "always_here": "Always here when you need us",
    "send_message": "Send us a Message",
    "first_name": "First Name",
    "last_name": "Last Name",
    "enter_first_name": "Enter your first name",
    "enter_last_name": "Enter your last name",
    "email_address": "Email Address",
    "enter_email_address": "Enter your email address",
    "phone_number": "Phone Number",
    "enter_phone_number": "Enter your phone number",
    "subject": "Subject",
    "what_can_we_help": "What can we help you with?",
    "message": "Message",
    "tell_us_requirements": "Tell us more about your requirements...",
    "send_message_button": "Send Message",
    
    // Footer
    "legal": "Legal",
    "terms_conditions": "Terms & Conditions",
    "privacy_policy": "Privacy Policy",
    "contact_us_footer": "Contact Us",
    "follow_us": "Follow Us",
    "facebook": "Facebook",
    "twitter": "Twitter",
    "instagram": "Instagram",
    "linkedin": "LinkedIn",
    "copyright_text": "© 2025 GoFarmlyConnect - Transforming Agriculture Through Technology. All rights reserved.",
    "made_with_love": "Made with ❤️ for Farmers",
    "proudly_indian": "🇮🇳 Proudly Indian",
    "serving_farmers": "Serving farmers across India",
    "empowering_farmers": "Empowering farmers with cutting-edge digital solutions for modern agriculture. Join the farming revolution today.",
    
    // FAQ Questions and Answers
    "faq_q1": "How do I register my farm on GoFarmlyConnect?",
    "faq_a1": "Registration is simple and free. Click on 'Get Started', fill in your basic farm details, upload required documents, and verify your mobile number. Our team will review and activate your account within 24 hours.",
    "faq_q2": "What documents can I file through the platform?",
    "faq_a2": "You can file all major agricultural documents including crop insurance applications, subsidy forms, loan applications, land records, soil health cards, and compliance certificates. Our system supports over 50+ document types.",
    "faq_q3": "Is my data secure on GoFarmlyConnect?",
    "faq_a3": "Absolutely. We use bank-grade encryption and follow strict data protection protocols. Your information is stored securely and never shared with third parties without your consent. We're also compliant with all government data protection regulations.",
    "faq_q4": "How accurate are the crop yield predictions?",
    "faq_a4": "Our AI-powered predictions have an accuracy rate of 85-90%. We use satellite imagery, weather data, soil conditions, and historical patterns to provide reliable forecasts. However, predictions should be used as guidance alongside your farming expertise.",
    "faq_q5": "Can I access GoFarmlyConnect offline?",
    "faq_a5": "Yes, our mobile app has offline capabilities. You can view your data, fill forms, and access tutorials without internet. Once you're back online, all changes sync automatically to the cloud.",
    "faq_q6": "What are the costs involved?",
    "faq_a6": "Basic features are completely free for all farmers. Premium features like advanced analytics, priority support, and additional storage are available through affordable subscription plans starting at ₹99/month.",
    "faq_q7": "How do I get technical support?",
    "faq_a7": "We offer 24/7 support through multiple channels - phone (1800-3010-1000), email, live chat, and WhatsApp. Our agricultural experts are always ready to help you with any technical or farming-related queries.",
    "faq_q8": "Can I integrate GoFarmlyConnect with other farming tools?",
    "faq_a8": "Yes, GoFarmlyConnect integrates with popular farming equipment, weather stations, and financial services. We have APIs available for custom integrations and partnerships with major agricultural technology providers."
  },
  hi: {
    // Navigation
    "about_us": "हमारे बारे में",
    "services": "सेवाएं",
    "video_tutorial": "वीडियो ट्यूटोरियल",
    "support": "सहायता",
    "login_register": "लॉगिन / रजिस्टर",
    "english": "English",
    "hindi": "हिन्दी",
    "marathi": "मराठी",
    
    // Hero Section
    "revolutionizing_agriculture": "🌾 कृषि में क्रांति",
    "welcome_to": "स्वागत है",
    "gofarmlyconnect": "गोफार्मलीकनेक्ट",
    "hero_description": "अपने कृषि संचालन को हमारे व्यापक डिजिटल प्लेटफॉर्म के साथ बदलें। हजारों किसानों से जुड़ें जिन्होंने हमारे नवाचार समाधानों का उपयोग करके अपनी उत्पादकता 40% बढ़ाई है।",
    "get_started_free": "मुफ्त शुरुआत करें",
    "watch_demo": "डेमो देखें",
    "active_farmers": "सक्रिय किसान",
    "trade_volume": "व्यापार मात्रा",
    "uptime": "अपटाइम",
    "latest_updates": "🚀 नवीनतम अपडेट",
    "ai_crop_prediction": "🌾 नई AI फसल भविष्यवाणी प्रणाली - उत्पादन 40% बढ़ाएं",
    "mobile_app_launched": "📱 मोबाइल ऐप लॉन्च - कहीं भी अपने खेत का प्रबंधन करें",
    "special_financing": "💰 छोटे किसानों के लिए विशेष वित्तपोषण - अभी आवेदन करें",
    
    // Services
    "our_services": "हमारी सेवाएं",
    "comprehensive_solutions": "व्यापक आयात निर्यात समाधान",
    "services_description": "आपके अंतर्राष्ट्रीय व्यापार संचालन को सुव्यवस्थित करने और अनुपालन सुनिश्चित करने के लिए आवश्यक सब कुछ",
    "gst_filing": "GST फाइलिंग",
    "gst_description": "आसान ऑनलाइन फाइलिंग के साथ अपने वस्तु और सेवा कर (GST) अनुपालन को सरल बनाएं।",
    "automated_gst_returns": "स्वचालित GST रिटर्न",
    "input_tax_credit": "इनपुट टैक्स क्रेडिट प्रबंधन",
    "reconciliation_tools": "सुलह उपकरण",
    "audit_support": "ऑडिट सहायता",
    "iec_registration": "IEC पंजीकरण",
    "iec_description": "अंतर्राष्ट्रीय व्यापार के लिए अपना आयात निर्यात कोड (IEC) जल्दी और आसानी से प्राप्त करें।",
    "new_iec_application": "नया IEC आवेदन",
    "iec_modification": "IEC संशोधन",
    "iec_renewal": "IEC नवीकरण",
    "consultation_services": "परामर्श सेवाएं",
    "dsc_procurement": "DSC खरीद",
    "dsc_description": "ऑनलाइन दस्तावेज़ प्रमाणीकरण के लिए अपना डिजिटल हस्ताक्षर प्रमाणपत्र (DSC) सुरक्षित करें।",
    "class3_dsc": "क्लास 3 DSC",
    "organization_dsc": "संगठन DSC",
    "individual_dsc": "व्यक्तिगत DSC",
    "renewal_services": "नवीकरण सेवाएं",
    "icegate_services": "ICEGATE सेवाएं",
    "icegate_description": "सीमा शुल्क निकासी और व्यापार संबंधी सेवाओं के लिए ICEGATE के साथ निर्बाध रूप से बातचीत करें।",
    "bill_of_entry": "बिल ऑफ एंट्री फाइलिंग",
    "shipping_bill": "शिपिंग बिल प्रसंस्करण",
    "duty_payment": "शुल्क भुगतान",
    "status_tracking": "स्थिति ट्रैकिंग",
    "adcode_registration": "AD कोड पंजीकरण",
    "adcode_description": "सुचारू निर्यात लेनदेन के लिए अपना अधिकृत डीलर (AD) कोड पंजीकृत करें।",
    "adcode_reg": "AD कोड पंजीकरण",
    "bank_linkage": "बैंक लिंकेज",
    "export_incentives": "निर्यात प्रोत्साहन",
    "compliance_checks": "अनुपालन जांच",
    "other_documents": "अन्य दस्तावेज़ फाइलिंग",
    "other_documents_description": "विभिन्न अन्य आयात-निर्यात संबंधी दस्तावेज़ फाइलिंग के लिए व्यापक सहायता।",
    "rcmc_application": "RCMC आवेदन",
    "meis_seis_claims": "MEIS/SEIS दावे",
    "epcg_license": "EPCG लाइसेंस",
    "advance_authorization": "अग्रिम प्राधिकरण",
    "learn_more": "और जानें",
    "ready_to_streamline": "अपने व्यापार संचालन को सुव्यवस्थित करने के लिए तैयार हैं?",
    "join_thousands": "हजारों आयातकों और निर्यातकों से जुड़ें जिन्होंने गोफार्मलीकनेक्ट के साथ अपने संचालन को डिजिटल बनाया है",
    "get_started_today": "आज ही शुरुआत करें",
    
    // Features
    "why_choose": "गोफार्मलीकनेक्ट क्यों चुनें",
    "built_for_modern": "आधुनिक के लिए निर्मित",
    "farmers": "किसान",
    "features_description": "हम समझते हैं कि किसानों को किन अनूठी चुनौतियों का सामना करना पड़ता है। इसीलिए हमने एक प्लेटफॉर्म बनाया है जो अत्याधुनिक तकनीक को गहरी कृषि विशेषज्ञता के साथ जोड़ता है।",
    "lightning_fast": "बिजली की तेज़ी से प्रसंस्करण",
    "lightning_description": "दस्तावेज़ों और आवेदनों को घंटों या दिनों में नहीं, मिनटों में प्रसंस्करण करें",
    "bank_grade_security": "बैंक-ग्रेड सुरक्षा",
    "security_description": "आपका डेटा एंटरप्राइज़-स्तरीय एन्क्रिप्शन के साथ सुरक्षित है",
    "expert_support": "विशेषज्ञ सहायता",
    "expert_description": "कृषि विशेषज्ञों से 24/7 ग्राहक सहायता",
    "proven_results": "सिद्ध परिणाम",
    "results_description": "हमारे उपयोगकर्ताओं के लिए औसतन 40% उत्पादकता वृद्धि",
    "save_time": "समय बचाएं",
    "time_description": "स्वचालन के साथ कागजी कार्रवाई का समय 80% तक कम करें",
    "compliance_100": "100% अनुपालन",
    "compliance_description": "सभी नियामक आवश्यकताओं के साथ अनुपालन में रहें",
    "happy_farmers": "खुश किसान",
    
    // Dashboard
    "dashboard": "डैशबोर्ड",
    "profile": "मेरी प्रोफाइल",
    "progress": "प्रगति",
    "documents": "दस्तावेज़",
    "settings": "सेटिंग्स",
    "registration": "पंजीकरण",
    "logout": "लॉगआउट",
    "welcome": "स्वागत",
    "complete_profile": "शुरू करने के लिए अपनी प्रोफाइल पूरी करें",
    "upload_document": "दस्तावेज़ अपलोड करें",
    "document_uploaded": "दस्तावेज़ सफलतापूर्वक अपलोड किया गया",
    "document_verified": "दस्तावेज़ सत्यापित",
    "document_rejected": "दस्तावेज़ अस्वीकृत",
    "pending_verification": "सत्यापन लंबित",
    "re_upload_required": "पुनः अपलोड आवश्यक",
    "profile_completion": "प्रोफाइल पूर्णता",
    "basic_information": "मूलभूत जानकारी",
    "required_documents": "आवश्यक दस्तावेज़",
    "email_verified": "ईमेल सत्यापित",
    "mobile_verified": "मोबाइल सत्यापित",
    "upload_successful": "अपलोड सफल",
    "upload_failed": "अपलोड असफल",
    "email_required": "ईमेल आवश्यक",
    "enter_email": "कृपया एक ईमेल पता दर्ज करें",
    "file_too_large": "फ़ाइल बहुत बड़ी",
    "file_size_limit": "कृपया 1MB से छोटी फ़ाइल अपलोड करें",
    "supported_formats": "समर्थित: PDF, JPG, PNG (अधिकतम 1MB)",
    "loading": "लोड हो रहा है...",
    "error": "त्रुटि",
    "failed_to_load": "प्रोफाइल डेटा लोड करने में असफल",
    "try_again": "पुनः प्रयास करें",
    
    // Dashboard specific
    "notifications": "सूचनाएं",
    "tutorials": "ट्यूटोरियल",
    "video_tutorials": "वीडियो ट्यूटोरियल",
    
    // Services/Import Export
    "simplify_import_export": "अपने आयात निर्यात को सरल बनाएं",
    "import_export_solutions": "आयात निर्यात समाधान",
     "simplify_your": "अपने आयात निर्यात",
    "import_export": " को सरल बनाएं",
    "hero_content_description": "आयात-निर्यात दस्तावेज़ीकरण, सीमा शुल्क निकासी और व्यापार अनुपालन के लिए एक संपूर्ण डिजिटल प्लेटफ़ॉर्म। हमारे स्वचालित फ़ाइलिंग सिस्टम से अपने शिपमेंट को 70% तेज़ी से प्रोसेस करें।",
    
    // Partners & Integrations
    "trusted_partners": "विश्वसनीय भागीदार",
    "our_partners_integrations": "हमारे भागीदार और एकीकरण",
    "partners_description": "एक व्यापक कृषि पारिस्थितिकी तंत्र बनाने के लिए प्रमुख सरकारी निकायों, वित्तीय संस्थानों और प्रौद्योगिकी भागीदारों के साथ काम करना",
    "government_partners": "सरकारी भागीदार",
    "banking_partners": "बैंकिंग भागीदार",
    "tech_integrations": "तकनीकी एकीकरण",
    "compliance_rate": "अनुपालन दर",
    
    // Testimonials  
    "success_stories": "सफलता की कहानियां",
    "what_farmers_say": "किसान हमारे बारे में क्या कहते हैं",
    "testimonials_description": "हजारों संतुष्ट किसानों से जुड़ें जिन्होंने गोफार्मलीकनेक्ट के साथ अपने कृषि संचालन को बदल दिया है",
    "average_rating": "औसत रेटिंग",
    "happy_farmers_count": "खुश किसान",
    "satisfaction_rate": "संतुष्टि दर",
    "support_available": "सहायता उपलब्ध",
    
    // Learn with us
    "learning_resources": "शिक्षण संसाधन",
    "learn_with_gofarmly": "गोफार्मलीकनेक्ट के साथ सीखें",
    "learn_description": "हमारे व्यापक वीडियो ट्यूटोरियल और विशेषज्ञ मार्गदर्शन के साथ आधुनिक कृषि तकनीकों और डिजिटल कृषि समाधानों में महारत हासिल करें",
    "view_all_tutorials": "सभी ट्यूटोरियल देखें",
    "watch_now": "अभी देखें",
    "views": "व्यूज",
    
    // Tutorial titles
    "farm_registration_title": "संपूर्ण फार्म पंजीकरण प्रक्रिया",
    "crop_management_title": "उन्नत फसल प्रबंधन तकनीकें",
    "financial_planning_title": "किसानों के लिए वित्तीय योजना",
    "market_analysis_title": "बाजार विश्लेषण और मूल्य रुझान",
    "digital_transformation_title": "कृषि में डिजिटल परिवर्तन",
    
    // Export Registration Tutorial - Hindi
    "overall_registration_progress": "समग्र पंजीकरण प्रगति",
    "journey_to_export_ready": "निर्यात-तैयार व्यवसाय बनने की आपकी यात्रा",
    "overall_progress": "समग्र प्रगति",
    "track_your_progress": "अपनी प्रगति ट्रैक करें",
    "learn_how_to_become_exporter": "निर्यातक कैसे बनें सीखें",
    "watch_step_by_step_tutorials": "निर्यात पंजीकरण प्रक्रिया को समझने के लिए हमारे चरणबद्ध ट्यूटोरियल देखें",
    "getting_started": "शुरुआत करना",
    "introduction_export_basics": "निर्यात व्यवसाय की मूल बातें परिचय",
    "min_watch": "मिनट देखें",
    "complete_registration_guide": "संपूर्ण पंजीकरण गाइड",
    "step_by_step_registration": "चरणबद्ध पंजीकरण प्रक्रिया वॉकथ्रू",
    "featured": "फीचर्ड",
    "document_preparation": "दस्तावेज़ तैयारी",
    "required_documents_preparation": "आवश्यक दस्तावेज़ और उन्हें कैसे तैयार करें",
    "view_all_video_tutorials": "सभी वीडियो ट्यूटोरियल देखें",
    "progress_remaining": "आपका निर्यात पंजीकरण पूरा करने के लिए शेष",
    "registration_complete": "🎉 पंजीकरण पूर्ण! निर्यात शुरू करने के लिए तैयार।",
    
    // Tutorial categories
    "getting_started_category": "शुरुआत करना",
    "management_category": "प्रबंधन",
    "analytics_category": "विश्लेषण",
    "finance_category": "वित्त",
    "logistics_category": "रसद",
    
    // FAQ
    "got_questions": "प्रश्न हैं?",
    "frequently_asked_questions": "अक्सर पूछे जाने वाले प्रश्न",
    "faq_description": "गोफार्मलीकनेक्ट की सुविधाओं, मूल्य निर्धारण और शुरुआत करने के तरीके के बारे में सामान्य प्रश्नों के उत्तर खोजें",
    "still_have_questions": "अभी भी प्रश्न हैं?",
    "support_team_help": "आपकी तलाश का उत्तर नहीं मिल रहा? हमारी सहायता टीम 24/7 आपकी सहायता के लिए यहां है",
    "contact_support": "सहायता से संपर्क करें",
    "schedule_call": "कॉल शेड्यूल करें",
    
    // Contact Us
    "get_in_touch": "संपर्क में रहें",
    "contact_us": "हमसे संपर्क करें",
    "contact_description": "अपने कृषि संचालन को बदलने के लिए तैयार? व्यक्तिगत मार्गदर्शन के लिए हमारे कृषि विशेषज्ञों से संपर्क करें",
    "helpdesk_24x7": "24x7 हेल्पडेस्क",
    "toll_free": "(टोल फ्री)",
    "available_round_clock": "चौबीसों घंटे उपलब्ध",
    "email_support": "ईमेल सहायता",
    "response_within_2hours": "2 घंटे के भीतर प्रतिक्रिया",
    "whatsapp_support": "व्हाट्सएप सहायता",
    "quick_assistance_chat": "चैट के माध्यम से त्वरित सहायता",
    "head_office": "मुख्य कार्यालय",
    "support_hours": "सहायता घंटे",
    "always_here": "जब आपको हमारी जरूरत हो तो हमेशा यहां",
    "send_message": "हमें संदेश भेजें",
    "first_name": "पहला नाम",
    "last_name": "अंतिम नाम",
    "enter_first_name": "अपना पहला नाम दर्ज करें",
    "enter_last_name": "अपना अंतिम नाम दर्ज करें",
    "email_address": "ईमेल पता",
    "enter_email_address": "अपना ईमेल पता दर्ज करें",
    "phone_number": "फोन नंबर",
    "enter_phone_number": "अपना फोन नंबर दर्ज करें",
    "subject": "विषय",
    "what_can_we_help": "हम आपकी कैसे सहायता कर सकते हैं?",
    "message": "संदेश",
    "tell_us_requirements": "अपनी आवश्यकताओं के बारे में हमें बताएं...",
    "send_message_button": "संदेश भेजें",
    
    // Footer
    "legal": "कानूनी",
    "terms_conditions": "नियम और शर्तें",
    "privacy_policy": "गोपनीयता नीति",
    "contact_us_footer": "हमसे संपर्क करें",
    "follow_us": "हमें फॉलो करें",
    "facebook": "फेसबुक",
    "twitter": "ट्विटर",
    "instagram": "इंस्टाग्राम",
    "linkedin": "लिंक्डइन",
    "copyright_text": "© 2025 गोफार्मलीकनेक्ट - प्रौद्योगिकी के माध्यम से कृषि को बदलना। सर्वाधिकार सुरक्षित।",
    "made_with_love": "किसानों के लिए ❤️ के साथ बनाया गया",
    "proudly_indian": "🇮🇳 गर्व से भारतीय",
    "serving_farmers": "पूरे भारत में किसानों की सेवा",
    "empowering_farmers": "आधुनिक कृषि के लिए अत्याधुनिक डिजिटल समाधानों के साथ किसानों को सशक्त बनाना। आज ही कृषि क्रांति में शामिल हों।"
  },
  mr: {
    // Navigation
    "about_us": "आमच्याबद्दल",
    "services": "सेवा",
    "video_tutorial": "व्हिडिओ ट्यूटोरियल",
    "support": "सहाय्य",
    "login_register": "लॉगिन / नोंदणी",
    "english": "English",
    "hindi": "हिन्दी",
    "marathi": "मराठी",
    
    // Hero Section
    "revolutionizing_agriculture": "🌾 शेतीमध्ये क्रांती",
    "welcome_to": "स्वागत आहे",
    "gofarmlyconnect": "गोफार्मलीकनेक्ट",
    "hero_description": "आमच्या व्यापक डिजिटल प्लॅटफॉर्मसह तुमच्या शेती ऑपरेशन्सचे रूपांतर करा। हजारो शेतकऱ्यांना सामील व्हा ज्यांनी आमच्या नाविन्यपूर्ण उपायांचा वापर करून त्यांची उत्पादकता 40% वाढवली आहे.",
    "get_started_free": "विनामूल्य सुरुवात करा",
    "watch_demo": "डेमो पहा",
    "active_farmers": "सक्रिय शेतकरी",
    "trade_volume": "व्यापार मात्रा",
    "uptime": "अपटाइम",
    "latest_updates": "🚀 नवीनतम अपडेट्स",
    "ai_crop_prediction": "🌾 नवीन AI पीक अंदाज प्रणाली - उत्पादन 40% वाढवा",
    "mobile_app_launched": "📱 मोबाइल अॅप लॉन्च - कुठेही तुमच्या शेताचे व्यवस्थापन करा",
    "special_financing": "💰 लहान शेतकऱ्यांसाठी विशेष वित्तपुरवठा - आता अर्ज करा",
    
    // Services
    "our_services": "आमच्या सेवा",
    "comprehensive_solutions": "व्यापक आयात निर्यात उपाय",
    "services_description": "तुमच्या आंतरराष्ट्रीय व्यापार ऑपरेशन्स सुव्यवस्थित करण्यासाठी आणि अनुपालन सुनिश्चित करण्यासाठी आवश्यक असलेली प्रत्येक गोष्ट",
    "gst_filing": "GST फाइलिंग",
    "gst_description": "सोप्या ऑनलाइन फाइलिंगसह तुमचे वस्तू आणि सेवा कर (GST) अनुपालन सरल करा.",
    "automated_gst_returns": "स्वयंचलित GST रिटर्न",
    "input_tax_credit": "इनपुट टॅक्स क्रेडिट व्यवस्थापन",
    "reconciliation_tools": "सामंजस्य साधने",
    "audit_support": "ऑडिट सहाय्य",
    "iec_registration": "IEC नोंदणी",
    "iec_description": "आंतरराष्ट्रीय व्यापारासाठी तुमचा आयात निर्यात कोड (IEC) लवकर आणि सहजतेने मिळवा.",
    "new_iec_application": "नवीन IEC अर्ज",
    "iec_modification": "IEC बदल",
    "iec_renewal": "IEC नूतनीकरण",
    "consultation_services": "सल्लागार सेवा",
    "dsc_procurement": "DSC खरेदी",
    "dsc_description": "ऑनलाइन दस्तऐवज प्रमाणीकरणासाठी तुमचे डिजिटल स्वाक्षरी प्रमाणपत्र (DSC) सुरक्षित करा.",
    "class3_dsc": "वर्ग 3 DSC",
    "organization_dsc": "संघटना DSC",
    "individual_dsc": "वैयक्तिक DSC",
    "renewal_services": "नूतनीकरण सेवा",
    "icegate_services": "ICEGATE सेवा",
    "icegate_description": "सीमाशुल्क मंजुरी आणि व्यापार संबंधी सेवांसाठी ICEGATE शी अखंडपणे संवाद साधा.",
    "bill_of_entry": "बिल ऑफ एंट्री फाइलिंग",
    "shipping_bill": "शिपिंग बिल प्रक्रिया",
    "duty_payment": "शुल्क पेमेंट",
    "status_tracking": "स्थिती ट्रॅकिंग",
    "adcode_registration": "AD कोड नोंदणी",
    "adcode_description": "सुरळीत निर्यात व्यवहारांसाठी तुमचा अधिकृत डीलर (AD) कोड नोंदवा.",
    "adcode_reg": "AD कोड नोंदणी",
    "bank_linkage": "बँक लिंकेज",
    "export_incentives": "निर्यात प्रोत्साहन",
    "compliance_checks": "अनुपालन तपासणी",
    "other_documents": "इतर दस्तऐवज फाइलिंग",
    "other_documents_description": "विविध इतर आयात-निर्यात संबंधी दस्तऐवज फाइलिंगसाठी व्यापक सहाय्य.",
    "rcmc_application": "RCMC अर्ज",
    "meis_seis_claims": "MEIS/SEIS दावे",
    "epcg_license": "EPCG परवाना",
    "advance_authorization": "आगाऊ अधिकृतीकरण",
    "learn_more": "अधिक जाणून घ्या",
    "ready_to_streamline": "तुमच्या व्यापार ऑपरेशन्स सुव्यवस्थित करण्यास तयार आहात?",
    "join_thousands": "हजारो आयातदार आणि निर्यातदारांसह सामील व्हा ज्यांनी गोफार्मलीकनेक्टसह त्यांच्या ऑपरेशन्सचे डिजिटलीकरण केले आहे",
    "get_started_today": "आजच सुरुवात करा",
    
    // Features
    "why_choose": "गोफार्मलीकनेक्ट का निवडा",
    "built_for_modern": "आधुनिकसाठी निर्मित",
    "farmers": "शेतकरी",
    "features_description": "शेतकऱ्यांना कोणत्या अनन्य आव्हानांना सामोरे जावे लागते हे आम्हाला समजते. म्हणूनच आम्ही एक प्लॅटफॉर्म तयार केले आहे जे अत्याधुनिक तंत्रज्ञानाला खोल कृषी तज्ञतेसह जोडते.",
    "lightning_fast": "विजेसारखी जलद प्रक्रिया",
    "lightning_description": "तास किंवा दिवसांत नाही तर मिनिटांत दस्तऐवज आणि अर्जांवर प्रक्रिया करा",
    "bank_grade_security": "बँक-ग्रेड सिक्यूरिटी",
    "security_description": "तुमचा डेटा एंटरप्राइझ-स्तरीय एन्क्रिप्शनसह संरक्षित आहे",
    "expert_support": "तज्ञ सहाय्य",
    "expert_description": "कृषी तज्ञांकडून 24/7 ग्राहक सहाय्य",
    "proven_results": "सिद्ध परिणाम",
    "results_description": "आमच्या वापरकर्त्यांसाठी सरासरी 40% उत्पादकता वाढ",
    "save_time": "वेळ वाचवा",
    "time_description": "ऑटोमेशनसह कागदी कामकाजाचा वेळ 80% पर्यंत कमी करा",
    "compliance_100": "100% अनुपालन",
    "compliance_description": "सर्व नियामक आवश्यकतांचे अनुपालन करा",
    "happy_farmers": "आनंदी शेतकरी",
    
    // Dashboard
    "dashboard": "डॅशबोर्ड",
    "profile": "माझी प्रोफाइल",
    "progress": "प्रगती",
    "documents": "दस्तऐवज",
    "settings": "सेटिंग्ज",
    "registration": "नोंदणी",
    "logout": "लॉगआउट",
    "welcome": "स्वागत",
    "complete_profile": "सुरु करण्यासाठी तुमची प्रोफाइल पूर्ण करा",
    "upload_document": "दस्तऐवज अपलोड करा",
    "document_uploaded": "दस्तऐवज यशस्वीरित्या अपलोड झाले",
    "document_verified": "दस्तऐवज सत्यापित",
    "document_rejected": "दस्तऐवज नाकारले",
    "pending_verification": "सत्यापन प्रलंबित",
    "re_upload_required": "पुन्हा अपलोड आवश्यक",
    "profile_completion": "प्रोफाइल पूर्णता",
    "basic_information": "मूलभूत माहिती",
    "required_documents": "आवश्यक दस्तऐवज",
    "email_verified": "ईमेल सत्यापित",
    "mobile_verified": "मोबाइल सत्यापित",
    "upload_successful": "अपलोड यशस्वी",
    "upload_failed": "अपलोड अयशस्वी",
    "email_required": "ईमेल आवश्यक",
    "enter_email": "कृपया ईमेल पत्ता प्रविष्ट करा",
    "file_too_large": "फाइल खूप मोठी",
    "file_size_limit": "कृपया 1MB पेक्षा लहान फाइल अपलोड करा",
    "supported_formats": "समर्थित: PDF, JPG, PNG (कमाल 1MB)",
    "loading": "लोड होत आहे...",
    "error": "त्रुटी",
    "failed_to_load": "प्रोफाइल डेटा लोड करण्यात अयशस्वी",
    "try_again": "पुन्हा प्रयत्न करा",
    
    // Dashboard specific
    "notifications": "सूचना",
    "tutorials": "ट्यूटोरियल",
    "video_tutorials": "व्हिडिओ ट्यूटोरियल",
    
    // Services/Import Export
    "simplify_import_export": "तुमचा आयात निर्यात सरल करा",
    "import_export_solutions": "आयात निर्यात उपाय",
    "hero_content_description": "आयात-निर्यात दस्तऐवजीकरण, सीमाशुल्क मंजुरी आणि व्यापार अनुपालनासाठी संपूर्ण डिजिटल प्लॅटफॉर्म. आमच्या स्वयंचलित फाइलिंग सिस्टमसह तुमच्या शिपमेंटची प्रक्रिया ७०% जलद करा.",
    "simplify_your": "आपले सोपे करा",
    "import_export": "आयात आणि निर्यात",
    
    // Partners & Integrations
    "trusted_partners": "विश्वसनीय भागीदार",
    "our_partners_integrations": "आमचे भागीदार आणि एकीकरण",
    "partners_description": "व्यापक कृषी इकोसिस्टम तयार करण्यासाठी आघाडीच्या सरकारी संस्था, वित्तीय संस्था आणि तंत्रज्ञान भागीदारांसह काम करणे",
    "government_partners": "सरकारी भागीदार",
    "banking_partners": "बँकिंग भागीदार",
    "tech_integrations": "तंत्रज्ञान एकीकरण",
    "compliance_rate": "अनुपालन दर",
    
    // Testimonials  
    "success_stories": "यशाच्या कथा",
    "what_farmers_say": "शेतकरी आमच्याबद्दल काय म्हणतात",
    "testimonials_description": "हजारो समाधानी शेतकऱ्यांसह सामील व्हा ज्यांनी गोफार्मलीकनेक्टसह त्यांच्या कृषी कामकाजाचे रूपांतर केले आहे",
    "average_rating": "सरासरी रेटिंग",
    "happy_farmers_count": "आनंदी शेतकरी",
    "satisfaction_rate": "समाधान दर",
    "support_available": "सहाय्य उपलब्ध",
    
    // Learn with us
    "learning_resources": "शिक्षण संसाधने",
    "learn_with_gofarmly": "गोफार्मलीकनेक्टसह शिका",
    "learn_description": "आमच्या व्यापक व्हिडिओ ट्यूटोरियल आणि तज्ञ मार्गदर्शनासह आधुनिक कृषी तंत्रे आणि डिजिटल शेती उपायांवर प्रभुत्व मिळवा",
    "view_all_tutorials": "सर्व ट्यूटोरियल पहा",
    "watch_now": "आता पहा",
    "views": "दृश्ये",
    
    // Tutorial titles
    "farm_registration_title": "संपूर्ण शेत नोंदणी प्रक्रिया",
    "crop_management_title": "प्रगत पीक व्यवस्थापन तंत्रे",
    "financial_planning_title": "शेतकऱ्यांसाठी वित्तीय योजना",
    "market_analysis_title": "बाजार विश्लेषण आणि किंमतीचे कल",
    "digital_transformation_title": "शेतीमध्ये डिजिटल परिवर्तन",
    
    // Export Registration Tutorial - Marathi
    "overall_registration_progress": "एकूण नोंदणी प्रगती",
    "journey_to_export_ready": "निर्यात-तैयार व्यवसाय बनण्याचा तुमचा प्रवास",
    "overall_progress": "एकूण प्रगती",
    "track_your_progress": "तुमची प्रगती ट्रॅक करा",
    "learn_how_to_become_exporter": "निर्यातदार कसे बनावे ते शिका",
    "watch_step_by_step_tutorials": "निर्यात नोंदणी प्रक्रिया समजून घेण्यासाठी आमचे चरणबद्ध ट्यूटोरियल पहा",
    "getting_started": "सुरुवात करणे",
    "introduction_export_basics": "निर्यात व्यवसायाच्या मूलभूत गोष्टींचा परिचय",
    "min_watch": "मिनिट पहा",
    "complete_registration_guide": "संपूर्ण नोंदणी मार्गदर्शक",
    "step_by_step_registration": "चरणबद्ध नोंदणी प्रक्रिया वॉकथ्रू",
    "featured": "फीचर्ड",
    "document_preparation": "दस्तऐवज तयारी",
    "required_documents_preparation": "आवश्यक दस्तऐवज आणि ते कसे तयार करावे",
    "view_all_video_tutorials": "सर्व व्हिडिओ ट्यूटोरियल पहा",
    "progress_remaining": "तुमचे निर्यात नोंदणी पूर्ण करण्यासाठी शिल्लक",
    "registration_complete": "🎉 नोंदणी पूर्ण! निर्यात सुरू करण्यासाठी तयार।",
    
    // Tutorial categories
    "getting_started_category": "सुरुवात करणे",
    "management_category": "व्यवस्थापन",
    "analytics_category": "विश्लेषण",
    "finance_category": "वित्त",
    "logistics_category": "रसद",
    
    // FAQ
    "got_questions": "प्रश्न आहेत?",
    "frequently_asked_questions": "वारंवार विचारले जाणारे प्रश्न",
    "faq_description": "गोफार्मलीकनेक्टच्या वैशिष्ट्यांबद्दल, किंमतीबद्दल आणि कसे सुरुवात करावी याबद्दल सामान्य प्रश्नांची उत्तरे शोधा",
    "still_have_questions": "अजूनही प्रश्न आहेत?",
    "support_team_help": "तुम्हाला शोधत असलेले उत्तर सापडत नाही? आमची सहाय्य टीम तुमच्या मदतीसाठी 24/7 येथे आहे",
    "contact_support": "सहाय्याशी संपर्क साधा",
    "schedule_call": "कॉल शेड्यूल करा",
    
    // Contact Us
    "get_in_touch": "संपर्कात रहा",
    "contact_us": "आमच्याशी संपर्क साधा",
    "contact_description": "तुमच्या शेती कामकाजाचे रूपांतर करण्यास तयार आहात? वैयक्तिक मार्गदर्शनासाठी आमच्या कृषी तज्ञांशी संपर्क साधा",
    "helpdesk_24x7": "24x7 हेल्पडेस्क",
    "toll_free": "(टोल फ्री)",
    "available_round_clock": "चोवीस तास उपलब्ध",
    "email_support": "ईमेल सहाय्य",
    "response_within_2hours": "2 तासांत प्रतिसाद",
    "whatsapp_support": "व्हाट्सअप सहाय्य",
    "quick_assistance_chat": "चॅटद्वारे त्वरित मदत",
    "head_office": "मुख्य कार्यालय",
    "support_hours": "सहाय्य तास",
    "always_here": "तुम्हाला गरज असताना नेहमी येथे",
    "send_message": "आम्हाला संदेश पाठवा",
    "first_name": "पहिले नाव",
    "last_name": "आडनाव",
    "enter_first_name": "तुमचे पहिले नाव प्रविष्ट करा",
    "enter_last_name": "तुमचे आडनाव प्रविष्ट करा",
    "email_address": "ईमेल पत्ता",
    "enter_email_address": "तुमचा ईमेल पत्ता प्रविष्ट करा",
    "phone_number": "फोन नंबर",
    "enter_phone_number": "तुमचा फोन नंबर प्रविष्ट करा",
    "subject": "विषय",
    "what_can_we_help": "आम्ही तुमची कशी मदत करू शकतो?",
    "message": "संदेश",
    "tell_us_requirements": "तुमच्या गरजांबद्दल आम्हाला सांगा...",
    "send_message_button": "संदेश पाठवा",
    
    // Footer
    "legal": "कायदेशीर",
    "terms_conditions": "अटी आणि शर्ती",
    "privacy_policy": "गोपनीयता धोरण",
    "contact_us_footer": "आमच्याशी संपर्क साधा",
    "follow_us": "आम्हाला फॉलो करा",
    "facebook": "फेसबुक",
    "twitter": "ट्विटर",
    "instagram": "इंस्टाग्राम",
    "linkedin": "लिंक्डइन",
    "copyright_text": "© 2025 गोफार्मलीकनेक्ट - तंत्रज्ञानाद्वारे कृषीचे रूपांतर. सर्व हक्क राखीव.",
    "made_with_love": "शेतकऱ्यांसाठी ❤️ सह तयार केले",
    "proudly_indian": "🇮🇳 अभिमानाने भारतीय",
    "serving_farmers": "संपूर्ण भारतातील शेतकऱ्यांची सेवा",
    "empowering_farmers": "आधुनिक कृषीसाठी अत्याधुनिक डिजिटल समाधानांसह शेतकऱ्यांना सक्षम बनवणे. आजच शेती क्रांतीत सामील व्हा."
  }
}

interface LanguageProviderProps {
  children: ReactNode
}

export function LanguageProvider({ children }: LanguageProviderProps) {
  const [language, setLanguage] = useState<string>('en')

  useEffect(() => {
    // Load saved language preference
    const savedLanguage = localStorage.getItem('preferredLanguage') || 'en'
    setLanguage(savedLanguage)
  }, [])

  const changeLanguage = (lang: string) => {
    setLanguage(lang)
    localStorage.setItem('preferredLanguage', lang)
  }

  const t = (key: string): string => {
    return translations[language]?.[key] || translations['en']?.[key] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage: changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}
